# Buggy methods directory
Buggy_Methods=~/GiantRepair/data/gpt4o-mini/buggy_methods/

# Patch directory
Patch_Methods=~/GiantRepair/llm_patches/

# Java home for Linux
JAVA_8_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
JAVA_11_HOME=/usr/lib/jvm/java-11-openjdk-amd64

# Defects4J home for Linux
DEFECTS4J_HOME=/home/alo/defects4j

# Max number of abstracted code skeletons
MAX_SKELETON=3

# Max number of instanced patches for one skeleton.
MAX_INSTANCE_PER_SKELETON=200

# Max number of plausible patches
MAX_PATCH_NUMBER=20

# Repair time for each subject (in minutes)
TIMEOUT=300

# choice for mutation's combination options.
COMBINATION_OPTION=false

# Option for context_aware or random
CONTEXT_AWARE=false

# Option for rank generated patches or not
RANK_PATCHES=true

# Option for modification selection
SELECT_MODIFY=true

# system command for fault localization
CMD.TIMEOUT=/usr/bin/timeout
